In [7]:
from uszipcode import Zipcode
from uszipcode import SearchEngine

In [8]:
search = SearchEngine(simple_zipcode=True)

Start downloading data for simple zipcode database, total size 9MB ...
  1 MB finished ...
  2 MB finished ...
  3 MB finished ...
  4 MB finished ...
  5 MB finished ...
  6 MB finished ...
  7 MB finished ...
  8 MB finished ...
  9 MB finished ...
  10 MB finished ...
  Complete!

In [34]:
(search.by_coordinates(39.122229, -77.133578)[0]).zipcode

'20855'

In [12]:
sql = '''SELECT zipcode, latitude, longitude
FROM listing as l
WHERE l.zipcode = 0'''

In [14]:
cursor.execute(sql)
zips = cursor.fetchall()

In [26]:
float(zips[1][1])

40.763090000000005

In [37]:
new_zip = []
for row in zips:
    new_zip.append(search.by_coordinates(float(row[1]), float(row[2]))[0].zipcode)

In [39]:
import pandas as pd

In [43]:
df =pd.DataFrame(new_zip)

In [45]:
df.to_csv('zipcodes.csv')

In [ ]:
UPDATE table_name  
SET column1 = value1, column2 = value2...., columnN = valueN  
WHERE [condition];